apiVersion: v1
kind: Service
metadata: 
  name: web-service
spec: 
  selector:
    app: web-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000