apiVersion: apps/v1
kind: Deployment
metadata:
  name: hnaj-deployment
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: nguyenphuocpham/hom-nay-an-gi:latest
        ports:
        - containerPort: 8000